version: '3.3'

services:

  nginx:
    build: ./servers/nginx/
    image: miricari-nginx-image
    #restart: always
    container_name: miricari-nginx
    depends_on:
      - tomcat
    networks:
      - app-net
    ports:
      - "80:8080"

  tomcat:
    build: ./servers/tomcat/
    image: miricari-tomcat-image
    #restart: always
    container_name: miricari-tomcat
    depends_on:
      - postgres
    networks:
      - app-net
    ports:
      - "8080:8080"
    volumes:
      - ./out/miricari:/usr/local/tomcat/webapps

  postgres:
    build: servers/postgres/
    image: miricari-postgres-image
    #restart: always
    container_name: miricari-postgres
    networks:
      - app-net
    environment:
      POSTGRES_USER: miricari
      POSTGRES_PASSWORD: password
    volumes:
      - ./servers/postgres/initdb:/docker-entrypoint-initdb.d

networks:
  app-net:
    driver: bridge
